### ISSUE TITLE
InfografiaHilo_JudithReynaCruzSantiago_4US

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/infografia-de-hilos-JudithReynaCS#2]
[INFOGRAFIAHILO_JUDITHREYNACRUZSANTIAGO_4US.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-JudithReynaCS/files/8376797/INFOGRAFIAHILO_JUDITHREYNACRUZSANTIAGO_4US.pdf)

**Comment by FedericoVictorianoSierra** [comment]
Calificación:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
